name: Build and Test app
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_PROJECT: ${{ 'Dinklebot/Dinklebot.xcodeproj' }}
      XC_SCHEME: ${{ 'Dinklebot' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Build and Test
      run: /usr/bin/xcodebuild test -project "$XC_PROJECT" -target "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11' clean test | xcpretty
